### ISSUE TITLE
Chrome 39

### ISSUE THREAD

**Issue by kos322** [thinkawitch/prices-onlinerby#1]
Chrome 39 установить не удалось. Переходить на dev канал или откатывать версию не хочу.

**Comment by thinkawitch** [comment]
Для пользователей Хрома есть его родное расширение - https://chrome.google.com/webstore/detail/onliner-%D0%B6%D0%B8%D0%B2/klokmhihmcmbdddhhjmnffjadfhkpkik?hl=en-US
